/*
Spotify Web API

You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetMultipleAlbums200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMultipleAlbums200Response{}

// GetMultipleAlbums200Response struct for GetMultipleAlbums200Response
type GetMultipleAlbums200Response struct {
	Albums []AlbumObject `json:"albums"`
}

// NewGetMultipleAlbums200Response instantiates a new GetMultipleAlbums200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMultipleAlbums200Response(albums []AlbumObject) *GetMultipleAlbums200Response {
	this := GetMultipleAlbums200Response{}
	this.Albums = albums
	return &this
}

// NewGetMultipleAlbums200ResponseWithDefaults instantiates a new GetMultipleAlbums200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMultipleAlbums200ResponseWithDefaults() *GetMultipleAlbums200Response {
	this := GetMultipleAlbums200Response{}
	return &this
}

// GetAlbums returns the Albums field value
func (o *GetMultipleAlbums200Response) GetAlbums() []AlbumObject {
	if o == nil {
		var ret []AlbumObject
		return ret
	}

	return o.Albums
}

// GetAlbumsOk returns a tuple with the Albums field value
// and a boolean to check if the value has been set.
func (o *GetMultipleAlbums200Response) GetAlbumsOk() ([]AlbumObject, bool) {
	if o == nil {
		return nil, false
	}
	return o.Albums, true
}

// SetAlbums sets field value
func (o *GetMultipleAlbums200Response) SetAlbums(v []AlbumObject) {
	o.Albums = v
}

func (o GetMultipleAlbums200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMultipleAlbums200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["albums"] = o.Albums
	return toSerialize, nil
}

type NullableGetMultipleAlbums200Response struct {
	value *GetMultipleAlbums200Response
	isSet bool
}

func (v NullableGetMultipleAlbums200Response) Get() *GetMultipleAlbums200Response {
	return v.value
}

func (v *NullableGetMultipleAlbums200Response) Set(val *GetMultipleAlbums200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMultipleAlbums200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMultipleAlbums200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMultipleAlbums200Response(val *GetMultipleAlbums200Response) *NullableGetMultipleAlbums200Response {
	return &NullableGetMultipleAlbums200Response{value: val, isSet: true}
}

func (v NullableGetMultipleAlbums200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMultipleAlbums200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


