/*
Spotify Web API

You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CopyrightObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CopyrightObject{}

// CopyrightObject struct for CopyrightObject
type CopyrightObject struct {
	// The copyright text for this content. 
	Text *string `json:"text,omitempty"`
	// The type of copyright: `C` = the copyright, `P` = the sound recording (performance) copyright. 
	Type *string `json:"type,omitempty"`
}

// NewCopyrightObject instantiates a new CopyrightObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCopyrightObject() *CopyrightObject {
	this := CopyrightObject{}
	return &this
}

// NewCopyrightObjectWithDefaults instantiates a new CopyrightObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCopyrightObjectWithDefaults() *CopyrightObject {
	this := CopyrightObject{}
	return &this
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *CopyrightObject) GetText() string {
	if o == nil || isNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CopyrightObject) GetTextOk() (*string, bool) {
	if o == nil || isNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *CopyrightObject) HasText() bool {
	if o != nil && !isNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *CopyrightObject) SetText(v string) {
	o.Text = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CopyrightObject) GetType() string {
	if o == nil || isNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CopyrightObject) GetTypeOk() (*string, bool) {
	if o == nil || isNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CopyrightObject) HasType() bool {
	if o != nil && !isNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CopyrightObject) SetType(v string) {
	o.Type = &v
}

func (o CopyrightObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CopyrightObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	if !isNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableCopyrightObject struct {
	value *CopyrightObject
	isSet bool
}

func (v NullableCopyrightObject) Get() *CopyrightObject {
	return v.value
}

func (v *NullableCopyrightObject) Set(val *CopyrightObject) {
	v.value = val
	v.isSet = true
}

func (v NullableCopyrightObject) IsSet() bool {
	return v.isSet
}

func (v *NullableCopyrightObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCopyrightObject(val *CopyrightObject) *NullableCopyrightObject {
	return &NullableCopyrightObject{value: val, isSet: true}
}

func (v NullableCopyrightObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCopyrightObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


